services:
  web:
    build: .
    ports:
      - "5173:5173" # Map the development server port
    volumes:
      - .:/app # Mount your project directory into the container
    command: npm run dev # Start the development server
